##
##  Dockerfile -- Docker Build Configuration
##

#   build arguments (early)
ARG         IMAGE_PREFIX=engelschall/
ARG         IMAGE_NAME=live-relay-vs-service
ARG         IMAGE_VERSION=1.0.6
ARG         IMAGE_RELEASE=20210213

#   derive image from a certain base image
FROM        ossrs/srs:v3.0-r3

