##
##  Dockerfile -- Docker Build Configuration
##

#   build arguments (early)
ARG         IMAGE_PREFIX=engelschall/
ARG         IMAGE_NAME=live-relay-vs-gateway
ARG         IMAGE_VERSION=0.9.0
ARG         IMAGE_RELEASE=20200517

#   derive image from a certain base image
FROM        dweomer/stunnel:latest

